# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/MIPS_stage1_v01.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
