@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 05 17:51:57 +0800 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_MIPS_CPU_ORI_behav -key {Behavioral:sim_1:Functional:tb_MIPS_CPU_ORI} -tclbatch tb_MIPS_CPU_ORI.tcl -view D:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/tb_MIPS_CPU_ORI_behav.wcfg -log simulate.log"
call xsim  tb_MIPS_CPU_ORI_behav -key {Behavioral:sim_1:Functional:tb_MIPS_CPU_ORI} -tclbatch tb_MIPS_CPU_ORI.tcl -view D:/Program_Files/MIPS CPU/race/Vivado2019/MIPS_v00/tb_MIPS_CPU_ORI_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
